algoritmo "ExercicioK"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Apresenta o valor caso ele não seja maior que 3.
// Autor(a)    : Nome do(a) aluno(a)

var
   valor_inteiro: inteiro

inicio

   escreva("Digite um valor inteiro: ")
   leia(valor_inteiro)

   se valor_inteiro <= 3 entao
      escreval("Valor informado: ", valor_inteiro)
   fimse

fimalgoritmo
