algoritmo "ExercicioI"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Verifica se um número é par ou ímpar.
// Autor(a)    : Nome do(a) aluno(a)

var
   numero: inteiro

inicio

   escreva("Digite um numero inteiro: ")
   leia(numero)

   se numero mod 2 = 0 entao
      escreval("O numero e par")
   senao
      escreval("O numero e impar")
   fimse

fimalgoritmo
