algoritmo "ExercicioA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

    celsius, fahrenheit: real

inicio

    escreva("Digite a temperatura em Celsius: ")
        leia(celsius)

    fahrenheit <- (9 * celsius + 160) / 5

   escreval("Temperatura em Fahrenheit: ", fahrenheit)

fimalgoritmo
