algoritmo "ExercicioC"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

    raio, altura, volume: real

inicio

    escreva("Digite o raio: ")
        leia(raio)

   escreva("Digite a altura: ")
        leia(altura)

    volume <- 3.14159 * raio * raio * altura

    escreval("Volume da lata: ", volume)

fimalgoritmo
