algoritmo "exercicioG"

var
   A, B, C, D: inteiro

inicio

   escreva("Digite o valor A: ")
    leia(A)

   escreva("Digite o valor B: ")
    leia(B)

   escreva("Digite o valor C: ")
    leia(C)

   escreva("Digite o valor D: ")
    leia(D)

   escreval("A + B = ", A + B)
   escreval("A + C = ", A + C)
   escreval("A + D = ", A + D)
   escreval("B + C = ", B + C)
   escreval("B + D = ", B + D)
   escreval("C + D = ", C + D)

   escreval("A * B = ", A * B)
   escreval("A * C = ", A * C)
   escreval("A * D = ", A * D)
   escreval("B * C = ", B * C)
   escreval("B * D = ", B * D)
   escreval("C * D = ", C * D)

fimalgoritmo
