algoritmo "Lista3ExercicioA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

numero: inteiro
incr: inteiro

inicio

    escreval("escreva um número: ")
        leia(numero)

    enquanto (incr < 11) faca
        escreval(numero + " x " + incr + " = " + numero * incr)
        incr <- incr + 1
    fimenquanto

fimalgoritmo
