algoritmo "Lista4ExercicioA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Apresenta o quadrado dos números de 15 a 200
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}

var

numero: inteiro

inicio

    numero <- 15

    repita

        escreval(numero, " ao quadrado = ", numero * numero)

        numero <- numero + 1

    ate numero > 200

fimalgoritmo
