algoritmo "Lista01310ExercicioAExtra"
// Disciplina : [Linguagem e Lógica de Programação
// Professor : [Nome do Professor
// Descrição : Aqui você descreve o que o programa faz! (função
// Autor(a) : Nome do(a) aluno(a
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL
var
    n1: inteiro
    n2: inteiro
    n3: inteiro
    n4: inteiro
    produto: inteiro
    soma: inteiro
inicio
    escreval("Escreva 4 números: ")
        leia(n1, n2, n3, n4)
    produto <- n1 * n3    soma <- n2 + n4   
    
    escreval("Produto entre N1 e o N3: ", produto)
    escreval("Soma entre N2 e N4: ", soma)

fimalgoritmo