algoritmo "Lista1Exercicioi"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

n1: inteiro
n2: inteiro
resultado: inteiro

inicio

    escreval("primeiro número: ")
        leia(n1)
    escreval("segundo número: ")
        leia(n2)

    resultado <- (n1 - n2) ^ 2

    escreva("o quadrado da diferença entre o n1 e o n2 é: ", resultado)


fimalgoritmo