algoritmo "Lista01ExercicioL"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

n1: inteiro
n2: inteiro
n3: inteiro
resultado: inteiro

inicio

    escreval("escreva 3 números: ")
        leia(n1, n2, n3)

    n1 <- n1 ^ 2
    n2 <- n2 ^ 2 
    n3 <- n3 ^ 2

    resultado <- n1 + n2 + n3

    escreva(resultado)

fimalgoritmo