algoritmo "Lista3ExercicioA"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

numero: inteiro
incr: inteiro

inicio

    escreval("escreva um número: ")
        leia(numero)

    para incr de 1 ate 10 faca
        escreval(incr, "x", numero, " = ", numero * incr)
    fimpara

fimalgoritmo