algoritmo "ExercicioBLista05"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

    incremento: inteiro
    numero: inteiro

inicio
    escreva("escreva um número qualquer para multiplica-lo até 10: ")
        leia(numero)

    para incremento de 1 ate 10 faca
        escreval(incremento + "x" + numero + " = " + incremento * numero)
    fimpara
fimalgoritmo
