algoritmo "Lista5ExercicioE"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Apresenta os números ímpares de 0 a 20
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}

var

    numero: inteiro

inicio
    para numero de 0 ate 20 faca

        se numero mod 2 <> 0 entao
            escreval(numero)
        fimse

    fimpara

fimalgoritmo
