algoritmo "Lista5ExercicioC"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Calcula a soma dos 100 primeiros números inteiros
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}

var

    numero: inteiro
    soma: inteiro

inicio
    soma <- 0

    para numero de 1 ate 100 faca

        soma <- soma + numero

    fimpara

    escreval("Soma = ", soma)

fimalgoritmo
