algoritmo "ExercicioALista05"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var
    expoente, potencia: inteiro

inicio

    potencia <- 1

    para expoente de 0 ate 15 faca
        escreval("3" + "^" + expoente + " = " + potencia)
        potencia <- potencia * 3

    fimpara

fimalgoritmo
