algoritmo "ExercicioALista05"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

incremento: inteiro

inicio

    para incremento de 15 ate 200 faca
        escreval(incremento ^ 2)
    fimpara

fimalgoritmo
