algoritmo "Lista5ExercicioF"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Apresenta os números divisíveis por 4 menores que 200
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}

var

numero: inteiro

inicio

    para numero de 1 ate 200 faca
        se numero mod 4 = 0 entao
            escreval(numero)
        fimse
    fimpara

fimalgoritmo
