algoritmo "Exercicio14"
// Disciplina : [Linguagem e Lógica de Programaç
// Professor : [Nome do Profess
// Descrição : Aqui você descreve o que o programa faz! (funç
// Autor(a) : Nome do(a) aluno
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATU
var
    numero: inteiro
inicio
    escreval("Escreva um número")
        leia(numero)    
    
    se (numero > 10) entao
        escreva("MAIOR QUE 10!")
    senao
        escreva("NÃO É MAIOR QUE 10!")
    fimse

fimalgoritmo