algoritmo "Exercicio33"
// Disciplina : [Linguagem e Lógica de Programação
// Professor : [Nome do Professor
// Descrição : Aqui você descreve o que o programa faz! (função
// Autor(a) : Nome do(a) aluno(a
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL
var
    n1: inteiro
    n2: inteiro
inicio
    escreval("escreva dois números: ")
        leia(n1, n2)
    se (n1 = n2) entao
        escreval("Números iguais")
     senao
        se (n1 > n2) entao
            escreva("Primeiro é maior")
         senao
            escreva("Segundo é maior")
        fimse
    fimse

fimalgoritmo