algoritmo "Exercicio27"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

numero: real

inicio

    escreval("escreva um número: ")
        leia(numero)
    
    se (numero < 0) entao
        escreva("negativo")
    senao
        escreva("positivo")
    fimse
    

fimalgoritmo