algoritmo "Exercicio13"
// Disciplina : [Linguagem e Lógica de Programaç
// Professor : [Nome do Profess
// Descrição : Aqui você descreve o que o programa faz! (funç
// Autor(a) : Nome do(a) aluno
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATU
var
    nota1: real
    nota2: real
    nota3: real
    nota_final: inteiro
inicio
    escreval("coloque as 3 notas do aluno para calcular a média: ")
        leia(nota1, nota2, nota3)
    nota_final <- (nota1 * 2 + nota2 * 3 + nota3 * 5) / 10    escreva("a nota final do aluno é: ", nota_final)

fimalgoritmo