algoritmo "Exercicio7"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL}
var

anos: inteiro
meses: inteiro
dias: inteiro
total_dias: inteiro

inicio

escreval("Digite a sua idade em anos, meses e dias:")
leia(anos, meses, dias)
total_dias <- (anos * 365) + (meses * 30) + dias
escreval("A sua idade em dias é: ", total_dias) 


fimalgoritmo