algoritmo "Exercicio5"
// Disciplina : [Linguagem e Lógica de Programaç
// Professor : [Nome do Profess
// Descrição : Aqui você descreve o que o programa faz! (funç
// Autor(a) : Nome do(a) aluno
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATU
var
    base: real
    altura: real
    area: real
inicio
    escreval("Digite a base do retângulo: ")
        leia(base)
    escreval("Digite a altura do retângulo: ")
        leia(altura)
    area <- base * altura    
    escreval("A área do retângulo é: ", area, "cm²")
// PRECISA USAR . AO INVÉS DE , para separar os decimais, caso contrário o programa não funciona corretamente.

fimalgoritmo