algoritmo "Exercicio15"
// Disciplina : [Linguagem e Lógica de Program
// Professor : [Nome do Profe
// Descrição : Aqui você descreve o que o programa faz! (fu
// Autor(a) : Nome do(a) alu
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_A
var
    numero: inteiro
inicio
    escreval("Escreva um número: ")
        leia(numero)
    se (numero > 0) entao
        escreva("número positivo")
     senao
        escreva("número negativo")
    fimse

fimalgoritmo