algoritmo "Exercicio33"
// Disciplina : [Linguagem e Lógica de Programação
// Professor : [Nome do Professor
// Descrição : Aqui você descreve o que o programa faz! (função
// Autor(a) : Nome do(a) aluno(a
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL
var
    numero1: inteiro
    numero2: inteiro
inicio
    escreval("escreva dois números: ")
        leia(numero1, numero2)
    se (numero1 = numero2) entao
        escreval("Números iguais")
     senao
        se (numero1 > numero2) entao
            escreva("Primeiro é maior")
         senao
            escreva("Segundo é maior")
        fimse
    fimse

fimalgoritmo
