algoritmo "Exercicio12"
// Disciplina : [Linguagem e Lógica de Programação
// Professor : [Nome do Professor
// Descrição : Aqui você descreve o que o programa faz! (função
// Autor(a) : Nome do(a) aluno(a
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL
var
    temp_fahrenheit: real
    temp_celsius: real
inicio
    escreval("temperatura em fahrenheit: ")
        leia(temp_fahrenheit)
    temp_celsius <- 5 / 9 * (temp_fahrenheit-32) 
    escreva("A conversão para Celsius é: ", temp_celsius)
fimalgoritmo