algoritmo "Exercicio6"
// Disciplina : [Linguagem e Lógica de Programação
// Professor : [Nome do Professor
// Descrição : Aqui você descreve o que o programa faz! (função
// Autor(a) : Nome do(a) aluno(a
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUAL
var
    numero1: inteiro
inicio
    escreval("digite um número:")
        leia(numero1)
    escreva("o antecessor do número digitado é: ", numero1 - 1)

fimalgoritmo