algoritmo "exercicio45"

// Disciplina : [Linguagem e Lógica de Programaçã
// Professor : [Nome do Professo
// Descrição : Aqui você descreve o que o programa faz! (funçã
// Autor(a) : Nome do(a) aluno(
// Data atual : ${DATA_ATUAL}/${MES_ATUAL}/${ANO_ATUA

var
   a, b: real

inicio

   escreva("Digite o primeiro valor: ")
   leia(a)

   escreva("Digite o segundo valor: ")
   leia(b)

   enquanto b = 0 faca
      escreva("Digite o segundo valor novamente: ")
      leia(b)
   fimenquanto

   escreval("Resultado: ", a / b)

fimalgoritmo
